<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__zipcode</name>
   <tag></tag>
   <elementGuidId>7cc8ca10-76e0-4daf-9e96-e9bdf65a73f3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#inputZipcode</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@type = 'text' and @placeholder = 'Example: 73301' and @name = 'zipcode']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='inputZipcode']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>bf156aff-0c55-422d-bac3-2fec582faf2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> demographic-input</value>
      <webElementGuid>750c0836-4a89-45e2-b6a2-2b833d2192b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c2041e37-e854-449c-951e-3456cc8333cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>inputZipcode</value>
      <webElementGuid>c9e963e1-618b-4ae7-ad5c-3e1231bb8b22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Example: 73301</value>
      <webElementGuid>e8b5fef3-21ed-47bf-a66b-793827f4767a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>zipcode</value>
      <webElementGuid>4dbd2792-5c74-46e4-9023-9aedd61a0166</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;inputZipcode&quot;)</value>
      <webElementGuid>f3cf050f-b175-4db8-a771-8cae2fb00ed8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='inputZipcode']</value>
      <webElementGuid>8f9aa99d-7407-481c-8a70-bdd61e02ea0f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/form/div/div/div[2]/div[5]/div/div[3]/div/div[2]/input</value>
      <webElementGuid>bc1f60c2-db33-4439-86c4-87a6351be7cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div[3]/div/div[2]/input</value>
      <webElementGuid>d9c2e9ee-bd4c-4fe8-a809-eff69ef63157</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'inputZipcode' and @placeholder = 'Example: 73301' and @name = 'zipcode']</value>
      <webElementGuid>7260f401-6102-4582-8e94-abf5dc517de5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
