<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__role</name>
   <tag></tag>
   <elementGuidId>217dc3aa-0b5c-4bc5-8659-5ba0d397f834</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#inputrolesenior</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='inputrolesenior']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>46cf08bd-e521-4b85-b134-897229982561</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>login-input-role </value>
      <webElementGuid>5b7525ed-6337-455e-aab6-af29276627db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>inputrolesenior</value>
      <webElementGuid>83e1be02-b785-4e36-aa17-04933cdeb81f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>role</value>
      <webElementGuid>5316fe35-74ce-4fa7-94be-2db622c777a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>58e98cd8-03fe-4ac1-aa46-5381d4ef323b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Senior</value>
      <webElementGuid>488cf248-a7fb-4e99-a419-e4bf70925e10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;inputrolesenior&quot;)</value>
      <webElementGuid>466b8b9e-2785-485b-b79a-d5532f4dd89c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='inputrolesenior']</value>
      <webElementGuid>0940deb1-b2e8-4aaa-a1fc-d8b259f42c05</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div/div/div/div/form/div/div[5]/div/div/input</value>
      <webElementGuid>78cfecf6-cb46-46fe-bceb-15554cbedafa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/input</value>
      <webElementGuid>a2c47b0e-1935-484e-9536-78a010285609</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'inputrolesenior' and @name = 'role' and @type = 'radio']</value>
      <webElementGuid>ca1e7e52-fc79-436a-8ebb-9b215c93fede</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
