<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__zipcode</name>
   <tag></tag>
   <elementGuidId>a759a249-09c2-49c7-ba89-f9a20a4ab53f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#inputzipcode</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='inputzipcode']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6ce63f3e-6d23-4c7f-9450-cc187dd37fe4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>login-input </value>
      <webElementGuid>63282624-d3ef-4bfe-93f6-249fbfc29a0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>inputzipcode</value>
      <webElementGuid>554934c5-3dc6-4a30-898c-c2adc8a0c0ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>9991d8fd-f4af-420d-ba78-cf58c4bb531e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>zipcode</value>
      <webElementGuid>b6f4deae-be99-40e9-99d2-f6c2004b834b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter ZIP code of your location</value>
      <webElementGuid>26f323e9-9087-4026-9b2b-ad17b16e3e0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;inputzipcode&quot;)</value>
      <webElementGuid>61a4e933-6605-4ff7-be06-d94ad8ce6b8d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='inputzipcode']</value>
      <webElementGuid>c5cfa675-1778-47cb-bbe4-e85785021b5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div/div/div/div/form/div/div[2]/input</value>
      <webElementGuid>2ff898ad-be30-4358-9356-05d3c110ce08</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>0b0cbca9-c3ee-4b55-aebc-b314da7cb1fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'inputzipcode' and @type = 'text' and @name = 'zipcode' and @placeholder = 'Enter ZIP code of your location']</value>
      <webElementGuid>1ba3280c-8ec6-4159-bdee-fc4ff8403db6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
